apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      initContainers:
        - name: install-cni
          env:
            - name: CNI_BIN_DIR
              value: /usr/lib/cni
            - name: CNI_CONF_DIR
              value: /etc/cni/net.d
          volumeMounts:
            - name: host-cni-lib
              mountPath: /host/usr/lib/cni
            - name: host-cni-lib
              mountPath: /host/secondary-bin-dir
      volumes:
        - name: host-cni-lib
          hostPath:
            path: /usr/lib/cni
            type: DirectoryOrCreate


