// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: planning.proto

package planningv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Brief         string                 `protobuf:"bytes,2,opt,name=brief,proto3" json:"brief,omitempty"`
	Ac            []string               `protobuf:"bytes,3,rep,name=ac,proto3" json:"ac,omitempty"` // Acceptance criteria (Gherkin)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryRequest) Reset() {
	*x = CreateStoryRequest{}
	mi := &file_planning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryRequest) ProtoMessage() {}

func (x *CreateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryRequest.ProtoReflect.Descriptor instead.
func (*CreateStoryRequest) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStoryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateStoryRequest) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *CreateStoryRequest) GetAc() []string {
	if x != nil {
		return x.Ac
	}
	return nil
}

type CreateStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	DorScore      int32                  `protobuf:"varint,3,opt,name=dor_score,json=dorScore,proto3" json:"dor_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryResponse) Reset() {
	*x = CreateStoryResponse{}
	mi := &file_planning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryResponse) ProtoMessage() {}

func (x *CreateStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryResponse.ProtoReflect.Descriptor instead.
func (*CreateStoryResponse) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStoryResponse) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *CreateStoryResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateStoryResponse) GetDorScore() int32 {
	if x != nil {
		return x.DorScore
	}
	return 0
}

type ListStoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoriesRequest) Reset() {
	*x = ListStoriesRequest{}
	mi := &file_planning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoriesRequest) ProtoMessage() {}

func (x *ListStoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoriesRequest.ProtoReflect.Descriptor instead.
func (*ListStoriesRequest) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{2}
}

type Story struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	DorScore      int32                  `protobuf:"varint,4,opt,name=dor_score,json=dorScore,proto3" json:"dor_score,omitempty"`
	Brief         string                 `protobuf:"bytes,5,opt,name=brief,proto3" json:"brief,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Story) Reset() {
	*x = Story{}
	mi := &file_planning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Story) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Story) ProtoMessage() {}

func (x *Story) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Story.ProtoReflect.Descriptor instead.
func (*Story) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{3}
}

func (x *Story) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *Story) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Story) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Story) GetDorScore() int32 {
	if x != nil {
		return x.DorScore
	}
	return 0
}

func (x *Story) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

type ListStoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stories       []*Story               `protobuf:"bytes,1,rep,name=stories,proto3" json:"stories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoriesResponse) Reset() {
	*x = ListStoriesResponse{}
	mi := &file_planning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoriesResponse) ProtoMessage() {}

func (x *ListStoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoriesResponse.ProtoReflect.Descriptor instead.
func (*ListStoriesResponse) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{4}
}

func (x *ListStoriesResponse) GetStories() []*Story {
	if x != nil {
		return x.Stories
	}
	return nil
}

type GetStoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryRequest) Reset() {
	*x = GetStoryRequest{}
	mi := &file_planning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryRequest) ProtoMessage() {}

func (x *GetStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryRequest.ProtoReflect.Descriptor instead.
func (*GetStoryRequest) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{5}
}

func (x *GetStoryRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type GetStoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Story         *Story                 `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	Ac            []string               `protobuf:"bytes,2,rep,name=ac,proto3" json:"ac,omitempty"`
	PlanJson      string                 `protobuf:"bytes,3,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"` // FSM state + available transitions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoryResponse) Reset() {
	*x = GetStoryResponse{}
	mi := &file_planning_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryResponse) ProtoMessage() {}

func (x *GetStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryResponse.ProtoReflect.Descriptor instead.
func (*GetStoryResponse) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{6}
}

func (x *GetStoryResponse) GetStory() *Story {
	if x != nil {
		return x.Story
	}
	return nil
}

func (x *GetStoryResponse) GetAc() []string {
	if x != nil {
		return x.Ac
	}
	return nil
}

func (x *GetStoryResponse) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

type TransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"` // FSM event name
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"` // User ID or system
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionRequest) Reset() {
	*x = TransitionRequest{}
	mi := &file_planning_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionRequest) ProtoMessage() {}

func (x *TransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionRequest.ProtoReflect.Descriptor instead.
func (*TransitionRequest) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{7}
}

func (x *TransitionRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *TransitionRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TransitionRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type TransitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Blocked       bool                   `protobuf:"varint,3,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // If blocked, guard failure reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionResponse) Reset() {
	*x = TransitionResponse{}
	mi := &file_planning_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionResponse) ProtoMessage() {}

func (x *TransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionResponse.ProtoReflect.Descriptor instead.
func (*TransitionResponse) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{8}
}

func (x *TransitionResponse) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *TransitionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TransitionResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *TransitionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_planning_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{9}
}

func (x *GetPlanRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type GetPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // Serialized plan with state, transitions, tasks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanResponse) Reset() {
	*x = GetPlanResponse{}
	mi := &file_planning_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanResponse) ProtoMessage() {}

func (x *GetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_planning_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanResponse.ProtoReflect.Descriptor instead.
func (*GetPlanResponse) Descriptor() ([]byte, []int) {
	return file_planning_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlanResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_planning_proto protoreflect.FileDescriptor

const file_planning_proto_rawDesc = "" +
	"\n" +
	"\x0eplanning.proto\x12\x11fleet.planning.v1\"P\n" +
	"\x12CreateStoryRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05brief\x18\x02 \x01(\tR\x05brief\x12\x0e\n" +
	"\x02ac\x18\x03 \x03(\tR\x02ac\"c\n" +
	"\x13CreateStoryResponse\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1b\n" +
	"\tdor_score\x18\x03 \x01(\x05R\bdorScore\"\x14\n" +
	"\x12ListStoriesRequest\"\x81\x01\n" +
	"\x05Story\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1b\n" +
	"\tdor_score\x18\x04 \x01(\x05R\bdorScore\x12\x14\n" +
	"\x05brief\x18\x05 \x01(\tR\x05brief\"I\n" +
	"\x13ListStoriesResponse\x122\n" +
	"\astories\x18\x01 \x03(\v2\x18.fleet.planning.v1.StoryR\astories\",\n" +
	"\x0fGetStoryRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\"o\n" +
	"\x10GetStoryResponse\x12.\n" +
	"\x05story\x18\x01 \x01(\v2\x18.fleet.planning.v1.StoryR\x05story\x12\x0e\n" +
	"\x02ac\x18\x02 \x03(\tR\x02ac\x12\x1b\n" +
	"\tplan_json\x18\x03 \x01(\tR\bplanJson\"Z\n" +
	"\x11TransitionRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\"w\n" +
	"\x12TransitionResponse\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\ablocked\x18\x03 \x01(\bR\ablocked\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"+\n" +
	"\x0eGetPlanRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\"%\n" +
	"\x0fGetPlanResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json2\xcf\x03\n" +
	"\x0fPlanningService\x12\\\n" +
	"\vCreateStory\x12%.fleet.planning.v1.CreateStoryRequest\x1a&.fleet.planning.v1.CreateStoryResponse\x12\\\n" +
	"\vListStories\x12%.fleet.planning.v1.ListStoriesRequest\x1a&.fleet.planning.v1.ListStoriesResponse\x12S\n" +
	"\bGetStory\x12\".fleet.planning.v1.GetStoryRequest\x1a#.fleet.planning.v1.GetStoryResponse\x12Y\n" +
	"\n" +
	"Transition\x12$.fleet.planning.v1.TransitionRequest\x1a%.fleet.planning.v1.TransitionResponse\x12P\n" +
	"\aGetPlan\x12!.fleet.planning.v1.GetPlanRequest\x1a\".fleet.planning.v1.GetPlanResponseBYZWgithub.com/underpass-ai/swe-ai-fleet/services/planning/gen/fleet/planning/v1;planningv1b\x06proto3"

var (
	file_planning_proto_rawDescOnce sync.Once
	file_planning_proto_rawDescData []byte
)

func file_planning_proto_rawDescGZIP() []byte {
	file_planning_proto_rawDescOnce.Do(func() {
		file_planning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_planning_proto_rawDesc), len(file_planning_proto_rawDesc)))
	})
	return file_planning_proto_rawDescData
}

var file_planning_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_planning_proto_goTypes = []any{
	(*CreateStoryRequest)(nil),  // 0: fleet.planning.v1.CreateStoryRequest
	(*CreateStoryResponse)(nil), // 1: fleet.planning.v1.CreateStoryResponse
	(*ListStoriesRequest)(nil),  // 2: fleet.planning.v1.ListStoriesRequest
	(*Story)(nil),               // 3: fleet.planning.v1.Story
	(*ListStoriesResponse)(nil), // 4: fleet.planning.v1.ListStoriesResponse
	(*GetStoryRequest)(nil),     // 5: fleet.planning.v1.GetStoryRequest
	(*GetStoryResponse)(nil),    // 6: fleet.planning.v1.GetStoryResponse
	(*TransitionRequest)(nil),   // 7: fleet.planning.v1.TransitionRequest
	(*TransitionResponse)(nil),  // 8: fleet.planning.v1.TransitionResponse
	(*GetPlanRequest)(nil),      // 9: fleet.planning.v1.GetPlanRequest
	(*GetPlanResponse)(nil),     // 10: fleet.planning.v1.GetPlanResponse
}
var file_planning_proto_depIdxs = []int32{
	3,  // 0: fleet.planning.v1.ListStoriesResponse.stories:type_name -> fleet.planning.v1.Story
	3,  // 1: fleet.planning.v1.GetStoryResponse.story:type_name -> fleet.planning.v1.Story
	0,  // 2: fleet.planning.v1.PlanningService.CreateStory:input_type -> fleet.planning.v1.CreateStoryRequest
	2,  // 3: fleet.planning.v1.PlanningService.ListStories:input_type -> fleet.planning.v1.ListStoriesRequest
	5,  // 4: fleet.planning.v1.PlanningService.GetStory:input_type -> fleet.planning.v1.GetStoryRequest
	7,  // 5: fleet.planning.v1.PlanningService.Transition:input_type -> fleet.planning.v1.TransitionRequest
	9,  // 6: fleet.planning.v1.PlanningService.GetPlan:input_type -> fleet.planning.v1.GetPlanRequest
	1,  // 7: fleet.planning.v1.PlanningService.CreateStory:output_type -> fleet.planning.v1.CreateStoryResponse
	4,  // 8: fleet.planning.v1.PlanningService.ListStories:output_type -> fleet.planning.v1.ListStoriesResponse
	6,  // 9: fleet.planning.v1.PlanningService.GetStory:output_type -> fleet.planning.v1.GetStoryResponse
	8,  // 10: fleet.planning.v1.PlanningService.Transition:output_type -> fleet.planning.v1.TransitionResponse
	10, // 11: fleet.planning.v1.PlanningService.GetPlan:output_type -> fleet.planning.v1.GetPlanResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_planning_proto_init() }
func file_planning_proto_init() {
	if File_planning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_planning_proto_rawDesc), len(file_planning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_planning_proto_goTypes,
		DependencyIndexes: file_planning_proto_depIdxs,
		MessageInfos:      file_planning_proto_msgTypes,
	}.Build()
	File_planning_proto = out.File
	file_planning_proto_goTypes = nil
	file_planning_proto_depIdxs = nil
}
