version: '3.8'

# Podman Compose configuration for SWE AI Fleet
# Run with: podman-compose up -d
# Or with Podman pods: podman play kube podman-pod.yaml

services:
  # NATS JetStream
  nats:
    image: docker.io/library/nats:2.10-alpine
    container_name: swe-nats
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # Monitoring
    command:
      - --jetstream
      - --store_dir=/data
      - --max_memory_store=1Gi
      - --max_file_store=10Gi
    volumes:
      - nats-data:/data
    userns_mode: "keep-id"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Planning Service
  planning:
    image: ghcr.io/underpass-ai/swe-fleet/planning:latest
    container_name: swe-planning
    ports:
      - "50051:50051"
    environment:
      - NATS_URL=nats://nats:4222
      - FSM_CONFIG=/app/config/agile.fsm.yaml
      - PORT=50051
    volumes:
      - ./config:/app/config:ro,z
    depends_on:
      - nats
    userns_mode: "keep-id"

  # Story Coach Service
  storycoach:
    image: ghcr.io/underpass-ai/swe-fleet/storycoach:latest
    container_name: swe-storycoach
    ports:
      - "50052:50052"
    environment:
      - PORT=50052
    userns_mode: "keep-id"

  # Workspace Scorer Service
  workspace:
    image: ghcr.io/underpass-ai/swe-fleet/workspace:latest
    container_name: swe-workspace
    ports:
      - "50053:50053"
    environment:
      - RIGOR_CONFIG=/app/config/rigor.yaml
      - PORT=50053
    volumes:
      - ./config:/app/config:ro,z
    userns_mode: "keep-id"

  # PO Planner UI
  ui:
    image: ghcr.io/underpass-ai/swe-fleet/po-ui:latest
    container_name: swe-ui
    ports:
      - "3000:80"
    userns_mode: "keep-id"

  # Redis (for context timeline)
  redis:
    image: docker.io/library/redis:7-alpine
    container_name: swe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data:z
    userns_mode: "keep-id"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Neo4j (for context graph)
  neo4j:
    image: docker.io/library/neo4j:5-community
    container_name: swe-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/underpassai
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j-data:/data:z
    userns_mode: "keep-id"
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nats-data:
  redis-data:
  neo4j-data:

