apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: swe-ai-fleet
spec:
  restartPolicy: Never
  containers:
  - name: gpu-test
    image: docker.io/nvidia/cuda:12.0.0-base-ubuntu22.04
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1

