apiVersion: batch/v1
kind: Job
metadata:
  name: nats-init-streams
  namespace: swe-ai-fleet
  labels:
    app: nats
    component: init
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: nats
        component: init
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      containers:
      - name: init-streams
        image: registry.underpassai.com/swe-ai-fleet/nats-jobs:v1.0.0
        imagePullPolicy: Always
        command: ["python", "/app/init_streams.py"]
        env:
        - name: NATS_URL
          value: "nats://nats.swe-ai-fleet.svc.cluster.local:4222"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

