---
# Microservices Deployments and Services
# Planning, StoryCoach, Workspace, and PO UI

# Planning Service
---
apiVersion: v1
kind: Service
metadata:
  name: planning
  namespace: swe-ai-fleet
  labels:
    app: planning
spec:
  type: ClusterIP
  selector:
    app: planning
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning
  namespace: swe-ai-fleet
  labels:
    app: planning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planning
  template:
    metadata:
      labels:
        app: planning
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: planning
          image: registry.underpassai.com/swe-fleet/planning:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: FSM_CONFIG
              value: "/app/config/agile.fsm.yaml"
            - name: PORT
              value: "50051"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
      volumes:
        - name: config
          configMap:
            name: fleet-config

# StoryCoach Service
---
apiVersion: v1
kind: Service
metadata:
  name: storycoach
  namespace: swe-ai-fleet
  labels:
    app: storycoach
spec:
  type: ClusterIP
  selector:
    app: storycoach
  ports:
    - port: 50052
      targetPort: 50052
      name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storycoach
  namespace: swe-ai-fleet
  labels:
    app: storycoach
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storycoach
  template:
    metadata:
      labels:
        app: storycoach
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: storycoach
          image: registry.underpassai.com/swe-fleet/storycoach:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
              name: grpc
          env:
            - name: PORT
              value: "50052"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 5

# Workspace Service
---
apiVersion: v1
kind: Service
metadata:
  name: workspace
  namespace: swe-ai-fleet
  labels:
    app: workspace
spec:
  type: ClusterIP
  selector:
    app: workspace
  ports:
    - port: 50053
      targetPort: 50053
      name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
  namespace: swe-ai-fleet
  labels:
    app: workspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: workspace
          image: registry.underpassai.com/swe-fleet/workspace:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50053
              name: grpc
          env:
            - name: PORT
              value: "50053"
            - name: RIGOR_CONFIG
              value: "/app/config/rigor.yaml"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 5
      volumes:
        - name: config
          configMap:
            name: fleet-config

# PO UI (React Frontend)
---
apiVersion: v1
kind: Service
metadata:
  name: po-ui
  namespace: swe-ai-fleet
  labels:
    app: po-ui
spec:
  type: ClusterIP
  selector:
    app: po-ui
  ports:
    - port: 80
      targetPort: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-ui
  namespace: swe-ai-fleet
  labels:
    app: po-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: po-ui
  template:
    metadata:
      labels:
        app: po-ui
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: nginx
          image: registry.underpassai.com/swe-fleet/ui:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
