---
# Context Service - Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: context
  namespace: swe-ai-fleet
  labels:
    app: context
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: context
  template:
    metadata:
      labels:
        app: context
        component: microservice
    spec:
      containers:
        - name: context
          image: registry.underpassai.com/swe-fleet/context:v0.1.0
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 50054
              protocol: TCP
          env:
            - name: GRPC_PORT
              value: "50054"
            - name: NEO4J_URI
              value: "bolt://neo4j:7687"
            - name: NEO4J_USER
              value: "neo4j"
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-auth
                  key: password
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 50054
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 50054
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3

---
# Context Service - Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: context
  namespace: swe-ai-fleet
  labels:
    app: context
    component: microservice
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50054
      targetPort: 50054
      protocol: TCP
  selector:
    app: context

---
# Context Service - Internal DNS (ExternalName)
apiVersion: v1
kind: Service
metadata:
  name: internal-context
  namespace: swe-ai-fleet
  labels:
    app: context
    component: internal-dns
spec:
  type: ExternalName
  externalName: context.swe-ai-fleet.svc.cluster.local

