---
# Context Service - Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: context
  namespace: swe-ai-fleet
  labels:
    app: context
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: context
  template:
    metadata:
      labels:
        app: context
        component: microservice
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: context
          image: registry.underpassai.com/swe-fleet/context:v0.2.1
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          ports:
            - name: grpc
              containerPort: 50054
              protocol: TCP
          env:
            - name: GRPC_PORT
              value: "50054"
            - name: NEO4J_URI
              value: "bolt://neo4j.swe-ai-fleet.svc.cluster.local:7687"
            - name: NEO4J_USER
              value: "neo4j"
            - name: NEO4J_PASSWORD
              value: "testpassword"  # TODO: Move to secret
            - name: REDIS_HOST
              value: "valkey.swe-ai-fleet.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: NATS_URL
              value: "nats://nats.swe-ai-fleet.svc.cluster.local:4222"
            - name: ENABLE_NATS
              value: "true"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests:
              cpu: 500m
              memory: 4Gi
            limits:
              cpu: 2000m
              memory: 12Gi
          livenessProbe:
            tcpSocket:
              port: 50054
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 50054
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3

---
# Context Service - Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: context
  namespace: swe-ai-fleet
  labels:
    app: context
    component: microservice
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50054
      targetPort: 50054
      protocol: TCP
  selector:
    app: context

---
# Context Service - Internal DNS (ExternalName)
apiVersion: v1
kind: Service
metadata:
  name: internal-context
  namespace: swe-ai-fleet
  labels:
    app: context
    component: internal-dns
spec:
  type: ExternalName
  externalName: context.swe-ai-fleet.svc.cluster.local

