---
# Neo4j StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: swe-ai-fleet
  labels:
    app: neo4j
    component: database
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
        component: database
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 7474
        runAsUser: 7474
        runAsGroup: 7474
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: neo4j
          image: docker.io/library/neo4j:5.14
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 7474
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 7474
              protocol: TCP
            - name: bolt
              containerPort: 7687
              protocol: TCP
          env:
            - name: NEO4J_AUTH
              value: "neo4j/testpassword"
            - name: NEO4J_dbms_memory_pagecache_size
              value: "4G"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "2G"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "8G"
            - name: NEO4J_server_default__listen__address
              value: "0.0.0.0"
            - name: NEO4J_server_bolt_listen__address
              value: "0.0.0.0:7687"
            - name: NEO4J_server_http_listen__address
              value: "0.0.0.0:7474"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-logs
              mountPath: /logs
          resources:
            requests:
              cpu: 500m
              memory: 4Gi
            limits:
              cpu: 2000m
              memory: 12Gi
          livenessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
        labels:
          app: neo4j
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 50Gi
    - metadata:
        name: neo4j-logs
        labels:
          app: neo4j
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi

---
# Neo4j Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: swe-ai-fleet
  labels:
    app: neo4j
    component: database
spec:
  type: ClusterIP
  clusterIP: None  # Headless for StatefulSet
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: 7687
      protocol: TCP
  selector:
    app: neo4j

---
# Neo4j Internal DNS (ExternalName)
apiVersion: v1
kind: Service
metadata:
  name: internal-neo4j
  namespace: swe-ai-fleet
  labels:
    app: neo4j
    component: internal-dns
spec:
  type: ExternalName
  externalName: neo4j.swe-ai-fleet.svc.cluster.local

