---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proto-docs-server
  namespace: swe-ai-fleet
  labels:
    app: proto-docs-server
    component: documentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proto-docs-server
  template:
    metadata:
      labels:
        app: proto-docs-server
        component: documentation
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/"
    spec:
      automountServiceAccountToken: false
      containers:
      - name: docserver
        image: registry.underpassai.com/swe-fleet/proto-docs-server:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: DOCS_PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 2
      restartPolicy: Always



