---
apiVersion: v1
kind: Service
metadata:
  name: proto-docs-server
  namespace: swe-ai-fleet
  labels:
    app: proto-docs-server
    component: documentation
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: proto-docs-server



