apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-executor
  namespace: swe-ai-fleet
  labels:
    app: ray-executor
    component: execution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-executor
  template:
    metadata:
      labels:
        app: ray-executor
        component: execution
    spec:
      containers:
      - name: ray-executor
        image: registry.underpassai.com/swe-fleet/ray-executor:v1.0.3
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50056
          protocol: TCP
        env:
        - name: RAY_ADDRESS
          value: "ray://ray-gpu-head-svc.ray.svc.cluster.local:10001"
        - name: NATS_URL
          value: "nats://nats.swe-ai-fleet.svc.cluster.local:4222"
        - name: GRPC_PORT
          value: "50056"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ray-executor
  namespace: swe-ai-fleet
  labels:
    app: ray-executor
spec:
  selector:
    app: ray-executor
  ports:
  - name: grpc
    port: 50056
    targetPort: grpc
  type: ClusterIP
