apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: swe
  labels:
    app: vllm
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: swe-ai-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      containers:
        - name: vllm
          image: docker.io/vllm/vllm-openai:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--model=TinyLlama/TinyLlama-1.1B-Chat-v1.0"
            - "--host=0.0.0.0"
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 24
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: "1"


