apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: swe
  labels:
    app: neo4j
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: swe-ai-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
        - name: neo4j
          image: docker.io/neo4j:5.26.12 # pin exact version for reproducibility
          imagePullPolicy: IfNotPresent
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-auth
                  key: auth
            # Must be true so env vars override config
            - name: NEO4J_server_config_override__with__environment
              value: "true"
            - name: NEO4J_server_default__listen__address
              value: "0.0.0.0"
            # Correct mapping (single "_" before enabled). Keep false while fixing typos; set true later.
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
            # Explicit memory sizing to avoid OOM within 2Gi limit
            - name: NEO4J_server_memory_heap_initial__size
              value: "1G"
            - name: NEO4J_server_memory_heap_max__size
              value: "1G"
            - name: NEO4J_server_memory_pagecache__size
              value: "512M"
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          # Probes tuned for slower first start
          startupProbe:
            tcpSocket:
              port: 7687
            periodSeconds: 10
            failureThreshold: 60   # ~10 minutes
          readinessProbe:
            tcpSocket:
              port: 7474
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 60   # ~5 minutes
          livenessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30   # ~5 minutes
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
