apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: swe
  labels:
    app: demo-frontend
    app.kubernetes.io/name: demo-frontend
    app.kubernetes.io/part-of: swe-ai-fleet
spec:
  type: ClusterIP
  selector:
    app: demo-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080


