apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: swe
  labels:
    app: redis
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: swe-ai-fleet
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379


