apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: swe
  labels:
    app: vllm
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: swe-ai-fleet
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
    - name: http
      port: 8000
      targetPort: 8000


