apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: swe
  labels:
    app: neo4j
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: swe-ai-fleet
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687



