"""Plan Preliminary value object."""

from dataclasses import dataclass

from planning.domain.value_objects.content.brief import Brief
from planning.domain.value_objects.content.title import Title
from planning.domain.value_objects.review.task_decision import TaskDecision


@dataclass(frozen=True)
class PlanPreliminary:
    """
    Value Object: Preliminary plan generated by backlog review ceremony.

    This plan is a proposal that the PO can approve/reject.
    If approved, it becomes an official Plan in Planning Service.

    Domain Invariants:
    - Title cannot be empty
    - Description cannot be empty
    - Acceptance criteria cannot be empty
    - Estimated complexity must be one of: LOW, MEDIUM, HIGH
    - Tasks outline: High-level tasks identified by councils (optional for backward compatibility)
    - Task decisions: Decision context for each task in tasks_outline

    Hybrid Flow:
    - Backlog Review: Generates tasks_outline (high-level task descriptions) + task_decisions (context)
    - Planning Meeting: Task Derivation Service expands outline into concrete tasks

    Semantic Relationships:
    - Each task in tasks_outline has corresponding TaskDecision explaining WHY it exists
    - TaskDecisions contain: decided_by, decision_reason, council_feedback
    - This enables context rehydration and observability
    """

    title: Title
    description: Brief
    acceptance_criteria: tuple[str, ...]
    technical_notes: str
    roles: tuple[str, ...]
    estimated_complexity: str  # LOW, MEDIUM, HIGH
    dependencies: tuple[str, ...]
    tasks_outline: tuple[str, ...] = ()  # High-level tasks identified by councils
    task_decisions: tuple[TaskDecision, ...] = ()  # Decision context for each task

    def __post_init__(self) -> None:
        """
        Fail-fast validation.

        Raises:
            ValueError: If validation fails
        """
        if not self.acceptance_criteria:
            raise ValueError("PlanPreliminary must have at least one acceptance criterion")

        if self.estimated_complexity not in ("LOW", "MEDIUM", "HIGH"):
            raise ValueError(
                f"Invalid estimated_complexity: {self.estimated_complexity}. "
                "Must be LOW, MEDIUM, or HIGH"
            )

    def __str__(self) -> str:
        """String representation for logging."""
        return f"PlanPreliminary(title={self.title}, complexity={self.estimated_complexity})"


