services:
  neo4j:
    image: docker.io/library/neo4j:5
    container_name: swe-ai-fleet-neo4j
    network_mode: "host"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/sweai1234}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    healthcheck:
      test: ["CMD", "bash", "-lc", "cypher-shell -u neo4j -p \"${NEO4J_AUTH##*/}\" 'RETURN 1;'" ]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:

