# Rigor Profiles for Workspace Scoring
# Defines quality thresholds for different levels of production readiness
# Higher levels = stricter requirements for build, test, coverage, static analysis

profiles:
  L0:
    name: Experimental
    description: Minimal checks for rapid prototyping and exploration
    weights:
      build: 0.40
      unit: 0.30
      static: 0.10
      e2e: 0.10
      coverage: 0.05
      lint: 0.05
    thresholds:
      build:
        ok: required
      unit:
        ok: required
        pass_rate: 0.70
      coverage:
        new_code_pct: 50
      static:
        quality_gate: warn_or_better  # WARN or OK
        max_critical: 999
      e2e:
        pass_rate: 0.60
      lint:
        max_errors: 20

  L1:
    name: Standard Production
    description: Balanced quality for most production features
    weights:
      build: 0.35
      unit: 0.25
      static: 0.20
      e2e: 0.10
      coverage: 0.05
      lint: 0.05
    thresholds:
      build:
        ok: required
      unit:
        ok: required
        pass_rate: 0.95
      coverage:
        new_code_pct: 70
      static:
        quality_gate: ok  # Must be OK
        max_critical: 5
        max_major: 20
      e2e:
        pass_rate: 0.85
      lint:
        max_errors: 5

  L2:
    name: High Quality
    description: High standards for sensitive production features
    weights:
      build: 0.30
      unit: 0.25
      static: 0.25
      e2e: 0.12
      coverage: 0.05
      lint: 0.03
    thresholds:
      build:
        ok: required
      unit:
        ok: required
        pass_rate: 0.98
      coverage:
        new_code_pct: 80
      static:
        quality_gate: ok
        max_critical: 2
        max_major: 10
      e2e:
        pass_rate: 0.95
      lint:
        max_errors: 2

  L3:
    name: Mission Critical
    description: Maximum rigor for security-critical or high-risk features
    weights:
      build: 0.25
      unit: 0.25
      static: 0.30
      e2e: 0.15
      coverage: 0.03
      lint: 0.02
    thresholds:
      build:
        ok: required
      unit:
        ok: required
        pass_rate: 1.0
      coverage:
        new_code_pct: 90
      static:
        quality_gate: ok
        max_critical: 0
        max_major: 5
      e2e:
        pass_rate: 1.0
      lint:
        max_errors: 0

# Scoring formula:
# Each dimension gets a 0-100 score based on meeting its thresholds
# Final score = weighted sum of dimension scores
# Gating decision:
#   - score >= 90: pass
#   - score >= 70: warn
#   - score < 70: block

gating_thresholds:
  pass: 90
  warn: 70
  block: 0

# Notes:
# - "required" means failure immediately blocks (score = 0)
# - pass_rate = passed / (passed + failed)
# - Static analysis queries SonarQube API for quality_gate status
# - Rigor level can be set per story or globally



