apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-mongodb
  namespace: swe-ai-fleet
  labels:
    app: e2e-mongodb
    e2e.underpass.ai/component: ephemeral-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e-mongodb
  template:
    metadata:
      labels:
        app: e2e-mongodb
        e2e.underpass.ai/component: ephemeral-deps
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mongodb
          image: docker.io/library/mongo:7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: e2e-mongodb
  namespace: swe-ai-fleet
  labels:
    app: e2e-mongodb
    e2e.underpass.ai/component: ephemeral-deps
spec:
  selector:
    app: e2e-mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-postgres
  namespace: swe-ai-fleet
  labels:
    app: e2e-postgres
    e2e.underpass.ai/component: ephemeral-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e-postgres
  template:
    metadata:
      labels:
        app: e2e-postgres
        e2e.underpass.ai/component: ephemeral-deps
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: docker.io/library/postgres:16-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: sandbox
            - name: POSTGRES_USER
              value: e2e
            - name: POSTGRES_PASSWORD
              value: e2e
          ports:
            - containerPort: 5432
              name: postgres
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U e2e -d sandbox -h 127.0.0.1 -p 5432"]
            initialDelaySeconds: 8
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: e2e-postgres
  namespace: swe-ai-fleet
  labels:
    app: e2e-postgres
    e2e.underpass.ai/component: ephemeral-deps
spec:
  selector:
    app: e2e-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-nats
  namespace: swe-ai-fleet
  labels:
    app: e2e-nats
    e2e.underpass.ai/component: ephemeral-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e-nats
  template:
    metadata:
      labels:
        app: e2e-nats
        e2e.underpass.ai/component: ephemeral-deps
    spec:
      automountServiceAccountToken: false
      containers:
        - name: nats
          image: docker.io/library/nats:2.10-alpine
          imagePullPolicy: IfNotPresent
          args:
            - "-js"
            - "--http_port"
            - "8222"
          ports:
            - containerPort: 4222
              name: nats
            - containerPort: 8222
              name: monitor
          readinessProbe:
            tcpSocket:
              port: 4222
            initialDelaySeconds: 4
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: e2e-nats
  namespace: swe-ai-fleet
  labels:
    app: e2e-nats
    e2e.underpass.ai/component: ephemeral-deps
spec:
  selector:
    app: e2e-nats
  ports:
    - name: nats
      port: 4222
      targetPort: 4222
    - name: monitor
      port: 8222
      targetPort: 8222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-rabbitmq
  namespace: swe-ai-fleet
  labels:
    app: e2e-rabbitmq
    e2e.underpass.ai/component: ephemeral-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e-rabbitmq
  template:
    metadata:
      labels:
        app: e2e-rabbitmq
        e2e.underpass.ai/component: ephemeral-deps
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rabbitmq
          image: docker.io/library/rabbitmq:3.13-management
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: e2e
            - name: RABBITMQ_DEFAULT_PASS
              value: e2e
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: mgmt
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: e2e-rabbitmq
  namespace: swe-ai-fleet
  labels:
    app: e2e-rabbitmq
    e2e.underpass.ai/component: ephemeral-deps
spec:
  selector:
    app: e2e-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: mgmt
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-kafka
  namespace: swe-ai-fleet
  labels:
    app: e2e-kafka
    e2e.underpass.ai/component: ephemeral-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e2e-kafka
  template:
    metadata:
      labels:
        app: e2e-kafka
        e2e.underpass.ai/component: ephemeral-deps
    spec:
      automountServiceAccountToken: false
      containers:
        - name: kafka
          image: docker.io/confluentinc/cp-kafka:7.6.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://e2e-kafka.swe-ai-fleet.svc.cluster.local:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@127.0.0.1:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"
          ports:
            - containerPort: 9092
              name: kafka
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 8
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: e2e-kafka
  namespace: swe-ai-fleet
  labels:
    app: e2e-kafka
    e2e.underpass.ai/component: ephemeral-deps
spec:
  selector:
    app: e2e-kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
---
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-ephemeral-kafka-init
  namespace: swe-ai-fleet
  labels:
    app: e2e-ephemeral-kafka-init
    e2e.underpass.ai/component: ephemeral-deps
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: e2e-ephemeral-kafka-init
        e2e.underpass.ai/component: ephemeral-deps
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      containers:
        - name: kafka-init
          image: docker.io/confluentinc/cp-kafka:7.6.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-ec"]
          args:
            - |
              BROKER="e2e-kafka.swe-ai-fleet.svc.cluster.local:9092"
              echo "Waiting for Kafka broker at ${BROKER}..."
              until kafka-topics --bootstrap-server "${BROKER}" --list >/dev/null 2>&1; do
                sleep 2
              done
              kafka-topics --bootstrap-server "${BROKER}" --create --if-not-exists --topic sandbox.events --partitions 1 --replication-factor 1
              kafka-topics --bootstrap-server "${BROKER}" --create --if-not-exists --topic dev.events --partitions 1 --replication-factor 1
              echo "Kafka initialization completed"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-ephemeral-rabbit-init
  namespace: swe-ai-fleet
  labels:
    app: e2e-ephemeral-rabbit-init
    e2e.underpass.ai/component: ephemeral-deps
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: e2e-ephemeral-rabbit-init
        e2e.underpass.ai/component: ephemeral-deps
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      containers:
        - name: rabbit-init
          image: docker.io/curlimages/curl:8.7.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-ec"]
          args:
            - |
              API="http://e2e-rabbitmq.swe-ai-fleet.svc.cluster.local:15672/api"
              AUTH="e2e:e2e"
              echo "Waiting for RabbitMQ API..."
              until curl -fsS -u "${AUTH}" "${API}/overview" >/dev/null; do
                sleep 2
              done
              for queue in sandbox.jobs dev.jobs; do
                curl -fsS -u "${AUTH}" \
                  -H "content-type:application/json" \
                  -X PUT "${API}/queues/%2F/${queue}" \
                  -d '{"auto_delete":false,"durable":false,"arguments":{}}' >/dev/null
              done
              echo "RabbitMQ initialization completed"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-ephemeral-mongo-seed
  namespace: swe-ai-fleet
  labels:
    app: e2e-ephemeral-mongo-seed
    e2e.underpass.ai/component: ephemeral-deps
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: e2e-ephemeral-mongo-seed
        e2e.underpass.ai/component: ephemeral-deps
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      containers:
        - name: mongo-seed
          image: docker.io/library/mongo:7.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-ec"]
          args:
            - |
              HOST="e2e-mongodb.swe-ai-fleet.svc.cluster.local:27017"
              echo "Waiting for MongoDB at ${HOST}..."
              until mongosh --host "${HOST}" --quiet --eval "db.runCommand({ ping: 1 })" >/dev/null 2>&1; do
                sleep 2
              done
              mongosh --host "${HOST}" --quiet --eval \
                'db = db.getSiblingDB("sandbox"); db.todos.updateOne({id:1}, {$set:{id:1,title:"seed",status:"open"}}, {upsert:true});'
              echo "MongoDB seed completed"
